apiVersion: v1
kind: Secret
metadata:
  name: cifs-secret
  namespace: longhorn-system
type: Opaque
data:
  CIFS_PASSWORD: {{ .Values.longhornContext.cifs_credentials.password | b64enc }}
  CIFS_USERNAME: {{ .Values.longhornContext.cifs_credentials.username | b64enc }}
